protected/models/Ministry.php
<?php
/**
 * This is the model class for table "ministry".
 *
 * The followings are the available columns in table 'ministry':
 * @property integer $ID
 * @property string $Name
 * @property string $Description
 * @property string $dateCreated
 * @property string $dateModified
 *
 * The followings are the available model relations:
 * @property Contribution[] $contributions
 * @property Event[] $events
 * @property Person[] $people
 */
class Ministry extends CActiveRecord
{
    /**
     * @return string the associated database table name
     */
    public function tableName()
    {
        return 'ministry';
    }

    /**
     * @return array validation rules for model attributes.
     */
    public function rules()
    {
        // NOTE: you should only define rules for those attributes that
        // will receive user inputs.
        return array(
            array('Name, Description', 'required'),
            array('Name', 'length', 'max'=>45),
            // The following rule is used by search().
            // @todo Please remove those attributes that should not be searched.
            array('ID, Name, Description, dateCreated, dateModified', 'safe', 'on'=>'search'),
            array('ID, Name, Description, dateCreated, dateModified', 'safe')
        );
    }

    /**
     * @return array relational rules.
     */
    public function relations()
    {
        // NOTE: you may need to adjust the relation name and the related
        // class name for the relations automatically generated below.
        return array(
            'contributions' => array(self::HAS_MANY, 'Contribution', 'Ministry'),
            'events' => array(self::HAS_MANY, 'Event', 'Ministry'),
            'people' => array(self::MANY_MANY, 'Person', 'ministryinvolvement(Ministry, Person)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels()
    {
        return array(
            'ID' => 'Ministry ID',
            'Name' => 'Name',
            'Description' => 'Description',
            'dateCreated' => 'Date Created',
            'dateModified' => 'Date Modified',
        );
    }

    /**
     * Retrieves a list of models based on the current search/filter conditions.
     *
     * Typical usecase:
     * - Initialize the model fields with values from filter form.
     * - Execute this method to get CActiveDataProvider instance which will filter
     * models according to data in model fields.
     * - Pass data provider to CGridView, CListView or any similar widget.
     *
     * @return CActiveDataProvider the data provider that can return the models
     * based on the search/filter conditions.
     */
    public function search()
    {
        // @todo Please modify the following code to remove attributes that should not be searched.

        $criteria=new CDbCriteria;

        $criteria->compare('ID',$this->ID);
        $criteria->compare('Name',$this->Name,true);
        $criteria->compare('Description',$this->Description,true);
        $criteria->compare('dateCreated',$this->dateCreated,true);
        $criteria->compare('dateModified',$this->dateModified,true);

        return new CActiveDataProvider($this, array(
            'criteria'=>$criteria,
        ));
    }

    /**
     * Returns the static model of the specified AR class.
     * Please note that you should have this exact method in all your CActiveRecord descendants!
     * @param string $className active record class name.
     * @return Ministry the static model class
     */
    public static function model($className=__CLASS__)
    {
        return parent::model($className);
    }
    
    private function getRelatedProvider($relation) {
        $relation = $this->getRelated($relation);
        $provider = new CArrayDataProvider($relation, array('keyField' => 'ID'));
        return $provider;
    }
    
    public function getAvailablePeople() {
        $allPeople = Person::model()->findAll();
        if (!empty($allPeople)) {
            //print_r("families detected       ");
            $criteria = new CDbCriteria();
            $criteria->addCondition('Ministry = ' . $this->ID);
            $Involvements = MinistryInvolvement::model()->findAll($criteria);
            if (!empty($Involvements)) {
                //print_r("Memberships detected     ");
                $involvementCriteria = new CDbCriteria();
                foreach ($Involvements as $Involvement) {
                    $involvementCriteria->addCondition('ID != ' . $Involvement->Person);
                }
                $involvementCriteria->order = 'firstName ASC';
                $availablePeople = Person::model()->findAll($involvementCriteria);
                if (!empty($availablePeople)) {
                    //print_r("returning available families     ");
                    return $availablePeople;
                }
                else {
                    //print_r("member of all families     ");
                    return NULL;
                }
            }
            else {
                //print_r("Member of no families     ");
                return $allPeople;
            }
        }
        else {
            //print_r("no families detected     ");
            return NULL;
        }
    }
    
    public function pullRelated() {
        $relatedData = array();
        
        $relatedData['events'] = $this->getRelatedProvider('events');
        $relatedData['contributions'] = $this->getRelatedProvider('contributions');
        $relatedData['people'] = $this->getRelatedProvider('people');
        $relatedData['availablePeople'] = $this->getAvailablePeople();
        
        return $relatedData;
    }
}

protected/controllers/MinistryController.php
<?php

class MinistryController extends RController
{
    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout='//layouts/column1';

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
            'rights', // rights management
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','view','loadAjaxModel'),
                'users'=>array('*'),
            ),
            array('allow', // allow authenticated user to perform 'create' and 'update' actions
                'actions'=>array('create','update','updateChild','deleteLinkRecord', 'newVol'),
                'users'=>array('@'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('admin','delete'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

    /**
     * Displays a particular model.
     * @param integer $id the ID of the model to be displayed
     */
    public function actionView($id)
    {
        $this->render('view',array(
            'model'=>$this->loadModel($id),
        ));
    }
    
    public function actionDeleteLinkRecord($thisID, $linkData, $linkName, $Entity) {
        if (!Yii::app()->request->isPostRequest || !Yii::app()->request->isAjaxRequest) {
            throw new CHttpException(400, 'Invalid request.');
        }
        $criteria = new CDbCriteria();
        $criteria->addCondition('Ministry = ' . $thisID . ' && ' . $linkName . ' = ' . $linkData);
        switch ($Entity) {
            case "Event":
                $toDelete = EventAttendance::model()->find($criteria);
                break;
            case "Family":
                $toDelete = FamilyMembership::model()->find($criteria);
                break;
            case "LifeEvent":
                $toDelete = LifeEventOccurrance::model()->find($criteria);
                break;
            case "Ministry":
                $toDelete = MinistryInvolvement::model()->find($criteria);
                break;
            case "Contribution":
                $toDelete = Contribution::model()->find($criteria);
                break;
            default:
                throw new CHttpException(400, 'Entity not recognised');
        }
        $toDelete->delete();
    }

    /**
     * Creates a new model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     */
    public function actionCreate()
    {
        $model = new Ministry;
        // If new ministry entry is posted
        if (isset($_POST['Ministry'])) {
            $params = array(); 
            parse_str($_POST['Ministry'], $params); // Parsing JSON object back to PHP array
            $model->attributes = $params['Ministry']; // Massive assignment to model from JSON parsed array
            if ($model->validate()) {
                $command = Yii::app()->db->createCommand();
                $command->insert('ministry', // $model->save() didn't work, threw that memory leak error we saw before
                    array( 'Name' => $model->Name // So we had to resort to the good old fashioned way
                         , 'Description' => $model->Description));
                /* To my knowledge, there's no decent way to get back a full 
                 * Ministry model after inserting to DB, so I had to get the model
                 * by selecting the row with the latest dateCreated stamp */
                $Details = Ministry::model()->findBySql("SELECT * FROM ministry "
                        . "ORDER BY dateCreated DESC "
                        . "LIMIT 1;");
                /* Why couldn't I just put through $model? Good question, all I 
                 * know is that it didn't work */
                $this->renderPartial('_viewAjax', array(
                'Details' => $Details,
                'relatedData' => $Details->pullRelated(),
                    ), false, true);
            } else {
                throw new CHttpException(400,"Ministry submission did not validate. Check controller, model and database.");
            }
            die();
        }
        
        //If wanting to create a new record
        if (isset($_POST['create'])) {
            $model = new Ministry();
            $this->renderPartial('_form', array(
                'model' => $model
                    ), false, true);
        }
    }
    
    /**
     * Updates a particular model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id the ID of the model to be updated
     */
    public function actionUpdate()
    {
        if (isset($_POST['scenario'])) {
            // Getting the values from Yii::app() request functionality, rather straight from _POST
            $val = Yii::app()->request->getParam('value');
            $pk = Yii::app()->request->getParam('pk');
            $attribute = Yii::app()->request->getParam('name');

            if (empty($attribute)) { // Throw exception if the attribute name is undefined for whatever reason - if this happens, it might be an error with js
                throw new CException(Yii::t('TbEditableSaver.editable', 'Property "attribute" should be defined.'));
            }
            if (empty($pk)) { // Throw exception if the primary key is undefined for whatever reason - if this happens, it might be an error with js
                throw new CException(Yii::t('TbEditableSaver.editable', 'Property "primaryKey" should be defined.'));
            }

            $model = CActiveRecord::model('Ministry')->findByPk($pk); // Initialise a model straight to the existing one based on the PK
            $model->setAttribute($attribute, $val); // Set the attribute in question to the new value
            $model->validate(); // Validate the model so as to generate any potential new errors from the attribute change

            if ($model->hasErrors()) { // If the model contains errors (boolean)
                $msg = ''; // String initialised to contain error messages
                foreach ($model->getErrors($attribute) as $attribute => $error) { // For each error for the attribute in question
                    $msg .= $error . "\n"; // Append msg with the error and a new line tag so as to display multiple potential errors
                }
                throw new CHttpException(400, $msg); // Throw a new CHttpException with our message
            }

            //If model validated with the new value
            $command = Yii::app()->db->createCommand(); // create a new DB command
            // Update the database
            $command->update('ministry', // UPDATE tablename
                    array($attribute => $val,), // ATTRIBUTES ...
                    'ID = :id', // WHERE ...
                    array(':id' => $pk)); // VALUES ...
        }
    }

    /**
     * Deletes a particular model.
     * If deletion is successful, the browser will be redirected to the 'admin' page.
     * @param integer $id the ID of the model to be deleted
     */
    public function actionDelete()
    {
        if (isset($_POST["pk"])) {
                if ($this->loadModel($_POST["pk"])->delete()) {
                    $this->renderPartial('_viewAjaxDeleted', array(
                        'deleted' => true
                            ), false, true);
                }
            }
    }

    /**
     * Lists all models.
     */
    public function actionIndex()
    {
        $dataProvider = new CActiveDataProvider('Ministry');
        $model = new Ministry('search');
        $model->unsetAttributes();
        if (isset($_GET['Ministry'])) {
            $model->attributes = $_GET['Ministry'];
        }
        
        $this->render('index', array('model' => $model,
            'dataProvider' => $dataProvider
        ));
    }

    /**
     * Manages all models.
     */
    public function actionAdmin()
    {
        $model=new Ministry('search');
        $model->unsetAttributes();  // clear any default values
        if (isset($_GET['Ministry'])) {
            $model->attributes=$_GET['Ministry'];
        }

        $this->render('admin',array(
            'model'=>$model,
        ));
    }
    
    public function actionUpdateChild() {
        if (isset($_POST['pk'])) {
            $Details = Ministry::model()->findByPk($_POST['pk']);
            $this->renderPartial('_viewAjax', array(
                'Details' => $Details,
                "relatedData" => $Details->pullRelated()
            ), false, true);
        }
    }
    
    public function actionNewVol() {
        if (!Yii::app()->request->isPostRequest || !Yii::app()->request->isAjaxRequest) {
            throw new CHttpException(400, 'Invalid request.');
        }
        if (isset($_POST['Person']) && isset($_POST['Capacity'])) {
            $Link = new MinistryInvolvement();
            $Link->setAttribute('Person', $_POST['Person']);
            $Link->setAttribute('Capacity', $_POST['Capacity']);
            $Link->setAttribute('Ministry', $_POST['Ministry']);
            $Link->setAttribute('Active', 'Active');
            if ($Link->validate()) {
                if (!$Link->save()) {

protected/views/ministry/_form.php
<div class='panel panel-group' id='formTitle'>
    <h1>New Ministry</h1>
</div>

<div class="panel panel-group" id="formBody">
    <?php $form=$this->beginWidget('booster.widgets.TbActiveForm',array(
            'id'=>'ministry-form',
            'enableClientValidation'=>true,
            'clientOptions' => array(
                'validateOnSubmit'=>true,
                'validateOnChange'=>true,
                'validateOnType'=>true,
            ),
            'htmlOptions' => array('class' => 'well'),
    )); ?>

    <p class="help-block">Fields with <span class="required">*</span> are required.</p>

    <?php echo $form->errorSummary($model); ?>

            <?php echo $form->textFieldGroup($model,'Name',array('widgetOptions'=>array('htmlOptions'=>array('class'=>'span5','maxlength'=>45)))); ?>

            <?php echo $form->textAreaGroup($model,'Description', array('widgetOptions'=>array('htmlOptions'=>array('rows'=>6, 'cols'=>50, 'class'=>'span8')))); ?>

    <div class="form-actions">
            <button class="btn btn-primary" id="newMSub" type="submit"><i class="glyphicon glyphicon-floppy-disk"></i><span>  </span>Save</button>
            <button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-repeat"></i><span>  </span>Reset</button>
    </div>

    <?php $this->endWidget(); ?>
</div>

protected/views/ministry/_viewAjax.php
<?php
/* @var $this MinistryController */
/* @var $Details Ministry */
/* @var $relatedData array */
?>
<div class="panel panel-group" id="accordion2">
    <h1>
        <?php  echo $Details->Name;
               /* if (Yii::app()->getModule('user')->isAdmin()) {
                echo '<button id="dP0" class="btn btn-danger pull-right" data-toggle="modal" data-target="#myModal"><i class="glyphicon glyphicon-trash"></i><span>  </span>Delete ' . $Details->Name . '</button>';
              } */
        ?>
    </h1>
</div>


<div class="modal fade" id="myModal">
  <div class="modal-dialog alert-danger">
    <div class="modal-content alert-danger">
      <div class="modal-header alert-danger">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h1><span class="glyphicon glyphicon-exclamation-sign"></span> Are you sure?</h1>
      </div>
      <div class="modal-body">
          <h4>Deleting this ministry is irreversibly permanent</h4>
          <h6>Only continue if you are sure you wish to delete their record</h6>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" id="dP" class="btn btn-danger pull-right" data-dismiss="modal"><i class="glyphicon glyphicon-trash"></i><span>  </span>Delete ministry</button>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Edit Details
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel panel-collapse collapse">
      <div class="panel panel-body">
                <?php
                    $this->widget('bootstrap.widgets.TbEditableDetailView', array(
                    'data' => $Details,
                    'url' => 'ministry/update',
                    'id' => 'editable',
                    'attributes' => array(
                        'Name',
                        'Description',
                    ),
                ));
                ?>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          <?php echo "Contributions"; ?>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <?php
            if (count($relatedData["contributions"]) < 1)
            {
                echo '<div class="alert alert-info" role="alert"><strong>Information: </strong> No contribution data for this ministry</div>';
            }
            else {
                $this->widget('bootstrap.widgets.TbGridView', array(
                        'id' => "contGrid",
                        'type' => 'striped bordered',
                        'dataProvider' => $relatedData['contributions'],
                        'selectableRows' => false,
                        'columns' => array(
                            array(
                                'name' => 'Amount ($)',
                                'value' => '$data->Amount'
                            ),
                            array(
                                'name' => 'Contributer',
                                'value' => function($data){$p = Person::model()->findByPk($data->Person); return $p->fullName;}
                            ),
                            array(
                                'name' => 'Family',
                                'value' => function($data){$f = Family::model()->findByPk($data->Family); return $f->Name;}
                            ),
                            array(
                                'name' => 'Date',
                                'value' => '$data->Date'
                            ),
                        )
                ));
            }
        ?>
      </div>
    </div>
  </div>
    <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          <?php echo "Events"; ?>
        </a>
      </h4>
    </div>
        <div id="collapseThree" class="panel-collapse collapse">
            <div class="panel-body" id="evtBody">
                <?php
                    if (count($relatedData["events"]) < 1)
                    {
                        echo '<div class="alert alert-info" role="alert"><strong>Information: </strong> This ministry has no events</div>';
                    }
                    else {
                        $this->widget('bootstrap.widgets.TbGridView', array(
                            'id' => "evtGrid",
                            'type' => 'striped bordered',
                            'dataProvider' => $relatedData['events'],
                            'selectableRows' => true,
                            'columns' => array(
                                array(
                                    'name' => 'Name',
                                    'value' => '$data->Name'
                                ),
                                array(
                                    'name' => 'Start Date',
                                    'value' => '$data->Start'
                                ),
                                array(
                                    'name' => 'End Date',
                                    'value' => '$data->End'
                                ),
                            )
                        ));
                    }
                ?>
            </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseFour">
          <?php echo "People"; ?>
        </a>
      </h4>
    </div>
        <div id="collapseFour" class="panel-collapse collapse">
            <div class="panel-body" id="pplBody">
                <?php
                    if ($relatedData['people']->getItemCount() < 1)
                    {
                        echo '<div class="alert alert-info" role="alert"><strong>Information: </strong> No people volunteer for this ministry</div>';
                    }
                    else {
                        $this->widget('bootstrap.widgets.TbGridView', array(
                        'id' => "pplGrid",
                        'type' => 'striped bordered',
                        'dataProvider' => $relatedData['people'],
                        'selectableRows' => true,
                        'htmlOptions' => array('style' => 'padding-bottom: 10px'),
                        'columns' => array(
                            array(
                                'name' => 'Capacity',
                                'value' => function($data)use($Details){
                                            $criteria = new CDbCriteria();
                                            $criteria->addCondition('Person = ' . $data->ID . ' AND Ministry = ' . $Details->ID);
                                            $mi = MinistryInvolvement::model()->find($criteria);
                                            return $mi->Capacity;
                                            }
                            ),
                            array(
                                'name' => 'Name',
                                'value' => '$data->firstName'
                            ),
                            array(
                                'name' => 'Address',
                                'value' => '$data->Address1'
                            ),
                            array(
                                'htmlOptions' => array('nowrap'=>'nowrap'),
                                'class'=>'bootstrap.widgets.TbButtonColumn',
                                'buttons' => array(
                                    'view' => array(
                                        'visible' => function($row,$data){false;},
                                    ),
                                    'update' => array(
                                        'visible' => function($data,$row){false;},
                                    ),
                                    'delete' => array(
                                        'url' => function($data) use ($Details){
                                                    return Yii::app()->createUrl('/ministry/deleteLinkRecord',
                                                    array('thisID'=>$Details->ID, 'linkData'=>$data->ID, 'linkName'=>'Person', 'Entity'=> 'Ministry')
                                                    );
                                                },
                                        'visible' => function($data,$row){return Yii::app()->getModule('user')->isAdmin();},
                                    )
                                )
                            )
                        )
                    ));
                    }
                    if ($relatedData['availablePeople'] !== NULL) {
                        $form = $this->beginWidget('booster.widgets.TbActiveForm', array(
                        'id' => 'newVolunteer-form',
                        'enableClientValidation' => true,
                        'clientOptions' => array(
                            'validateOnSubmit' => true,
                            'validateOnChange' => true,
                            'validateOnType' => true,
                        ),
                        'htmlOptions' => array('class' => 'well'),
                            )
                        );
                        echo '<div class="form-group">';
                        echo '<h4>Add a volunteer to ' . $Details->Name . '</h4>';
                        $list = CHtml::listData($relatedData['availablePeople'], 'ID', 'fullName');
                        echo CHtml::dropDownList('personDrop', '', $list, array('prompt' => 'Select a Person', 'class' => 'input-large form-control'));
                        echo CHtml::dropDownList('capacityDrop', '', array('Leader' => 'Leader', 'Volunteer' => 'Volunteer'), array('prompt' => 'Capacity Serving In', 'class' => 'input-large form-control'));
                        echo '<div class="form-actions" style="padding-top: 10px">';
                        echo '<button class="btn btn-primary" id="newPVol" type="submit"><i class="glyphicon glyphicon-floppy-disk"></i><span>  </span>Save</button>';
                        echo '<button class="btn btn-default" type="reset"><i class="glyphicon glyphicon-repeat"></i><span>  </span>Reset</button>';
                        echo '</div>';
                        echo '</div>';
                        $this->endWidget();
                    }
                    else {
                        echo '<div class="alert alert-info" role="alert"><strong>Information: </strong> No more people can be volunteered for this ministry</div>';
                    }
                    
                ?>
            </div>
    </div>
  </div>
</div>
<script>
    $(function(){
        $('#dP').click(function(){
            $('#myModal').on('hidden.bs.modal', function (e) {
                   var pK = <?php echo $Details->ID; ?>;
                   var jqxhr = $.ajax( {
                    type: 'POST',
                    url: 'ministry/delete',
                    data: { pk: pK },
                    })
                .done(function(data) {
                    $('#updateData').html(data);
                    $('#accordionDel').collapse();
                    $.notify("Successfully Deleted", "success");
                    $.fn.yiiGridView.update('minMainGrid');
                })
                .fail(function() {
                    console.log("Deleting the ministry failed. Check model, controller and database");
                })
            })
        });
        $('body').on('click', '#newPVol', function(e){
            e.preventDefault();
            var personElement = document.getElementById("personDrop");
            var Select = personElement.options[personElement.selectedIndex].value;
            var capacityElement = document.getElementById("capacityDrop");
            var selCap = capacityElement.options[capacityElement.selectedIndex].value;
            var jqxhr = $.ajax({
                type: 'POST',
                url: 'ministry/newVol',
                data: {Person: Select,
                       Ministry: <?php echo $Details->ID; ?>,
                       Capacity: selCap},
                cache: false
            })
            .done(function() {
                $.notify("Added " + personElement.options[capacityElement.selectedIndex].key + " as a volunteer", "success");
            })
            .fail(function() {
            });
        });
    });
</script>

protected/views/ministry/_viewAjaxDeleted.php
<div class="panel panel-group" id='accordionDel'>
    <div class="alert alert-info" role="alert">
            <h1>Click on another ministry to view its information</h1>
    </div>
</div>